### ISSUE TITLE
Ignore modules with pom packaging

### ISSUE THREAD

**Issue by reitzmichnicht** [gantsign/ktlint-maven-plugin#207]
Having maven multi module builds the parent module is normally of packaging type pom, so there are no source folders. But the kslint maven Plugin is passing the default source folders to ktlint which results in 3 warnings.

Kind regards
Michael

**Comment by freemanjp** [comment]
@reitzmichnicht, thanks for reporting this issue. There are reasons why you may have Kotlin files in a module with `pom` packaging (e.g. projects that have Maven and Gradle build scripts), so skipping `ktlint` entirely isn't an option. But for modules with `pom` packaging I've reduced the logging for missing directories from `WARN` to `DEBUG`. You can find this change in #209. This change is in the [0.9.24](https://github.com/gantsign/ktlint-maven-plugin/releases/tag/0.9.24) release of this plugin.

**Comment by reitzmichnicht** [comment]
Thank you for the quick fix, works now as expected
