### ISSUE TITLE
Documentation - 404 errors

### ISSUE THREAD

**Issue by jhult** [gantsign/ktlint-maven-plugin#283]
The `Goals` pages are returning 404 errors.

![image](https://user-images.githubusercontent.com/9849069/64368228-d89be080-cfe7-11e9-841a-c01f020f59d8.png)

**Comment by freemanjp** [comment]
@jhult thanks for reporting this issue. The documentation is fixed in the [1.2.2](https://github.com/gantsign/ktlint-maven-plugin/releases/tag/1.2.2) release.
