### ISSUE TITLE
Plain reporter throws an error: Invalid color parameter.

### ISSUE THREAD

**Issue by dibog** [gantsign/ktlint-maven-plugin#359]
The com.pinterest.ktlint.reporter.plain.PlainReporter throws an exception as the color is not provided by the com.github.gantsign.maven.plugin.ktlint.internal.MavenLogReporter.

This means that currently the following in the usage documentation does not work:

	<reporters>
	  <reporter>
		<name>plain</name>
		<output>${project.build.directory}/ktlint.txt</output>
		<properties>
		  <property>
			<name>group_by_file</name>
			<value>true</value>
		  </property>
		</properties>
	  </reporter>
	</reporters>

Even if I add

	<property>
		<name>shouldColorOutput</name>
		<value>false</value>
	</property>
	<property>
		<name>outputColor</name>
		<value>DARK_GRAY</value>
	</property>

**Comment by freemanjp** [comment]
@dibog thanks for reporting this issue, sorry it took so long to fix. You can find the fix for the issue in version [1.8.0](https://github.com/gantsign/ktlint-maven-plugin/releases/tag/1.8.0) of this role.
