### ISSUE TITLE
Editorconfig file no longer loaded since to update to ktlint 0.47.x

### ISSUE THREAD

**Issue by paul-dingemans** [gantsign/ktlint-maven-plugin#508]
Hi,

I am maintainer on the ktlint project. Due to a change in ktlint 0.47.x the ".editorconfig" is no longer loaded whenever a relative filepath is specified when calling the ktlint API. On https://github.com/gantsign/ktlint-maven-plugin/blob/main/src/main/kotlin/com/github/gantsign/maven/plugin/ktlint/internal/AbstractCheckSupport.kt#L191 the relative file path is specified when calling ktlint API. Can this please be change to an absolute path?

Following problems will most likely be resolved with this change:
* [ktlint #1603](https://github.com/pinterest/ktlint/issues/1603)
* #507

**Comment by freemanjp** [comment]
Hi @paul-dingemans, thanks for identifying the problem you can find the fix in version [1.15.1](https://github.com/gantsign/ktlint-maven-plugin/releases/tag/1.15.1) of this plugin.
