### ISSUE TITLE
Poorly constructed error on enum

### ISSUE THREAD

**Issue by JaxGibb-atlassian** [gantsign/ktlint-maven-plugin#525]
For code as per
```
    enum class Useless {
        one
        two,
        three
    }
```
produced an error of
**5:12 Expecting ';' after the last enum entry or '}' to close enum class body**
Obviously, if the missing comma is early in the list, this message doesn't help.

**Comment by freemanjp** [comment]
Hi, @JaxGibb-atlassian sorry for the late reply. That looks like an issue with [ktlint](https://github.com/pinterest/ktlint) itself rather than with the Maven plugin (this project is only for the Maven plugin).
