### ISSUE TITLE
ktlint update

### ISSUE THREAD

**Issue by sanyarnd** [gantsign/ktlint-maven-plugin#538]
https://github.com/pinterest/ktlint/releases/tag/0.48.2

hi, new version is out

**Comment by freemanjp** [comment]
Hi @sanyarnd, sorry for the delay, it was an awkward upgrade, version [1.16.0](https://github.com/gantsign/ktlint-maven-plugin/releases/tag/1.16.0) (supporting ktlink 0.48.2) is now available.
