### ISSUE TITLE
Update to 0.49

### ISSUE THREAD

**Issue by sanyarnd** [gantsign/ktlint-maven-plugin#549]
Hi, new version of ktlint was released few days ago

**Comment by freemanjp** [comment]
@sanyarnd thanks for reporting this issue. Unfortunately, there are many breaking changes in `ktlint` 0.49.0, so upgrading this Maven plugin will take longer than usual.

**Comment by sanyarnd** [comment]
Any updates?

**Comment by freemanjp** [comment]
@sanyarnd sorry for the delay, version `2.0.0` of this plugin now support ktlint `0.50.0`.
