### ISSUE TITLE
[documentation] README does not show quick usage

### ISSUE THREAD

**Issue by binkley** [gantsign/ktlint-maven-plugin#570]
Would you provide an immediate "how to use" section prominent in the README?

As a dev, one of the most prominent things I want to see in a project is `README.md` is instructions for quickly trying out. For JVM projects, this is how I can "kick the tires" with Maven and Gradle (Gradle not relevant here).

I'm OK to make a PR.

**Comment by freemanjp** [comment]
Hi @binkley, I get it, but there are a couple of problems:

1. The version number is a pain to handle with READMEs, most projects have a placeholder e.g. `<version>VERSION_NUMBER</version>`. Some opt for updating the README every time there's a release (so you can just copy and paste), but this creates noise in the git history and is a pain to automate.
2. This plugin doesn't have a single use case, some users may just want to format, some users may just want to check, some users may want to do both, and some may want to generate reports. Covering all 4 in a README would make it too long IMHO, if I only cover one people may miss the other options.

Linking to the generated Maven site solves both of these issues. Not a perfect solution, but I don't see a better alternative.

**Comment by binkley** [comment]
@freemanjp That makes sense. Thanks!
