### ISSUE TITLE
Ktlint 1.3.0 release

### ISSUE THREAD

**Issue by sanyarnd** [gantsign/ktlint-maven-plugin#628]
https://github.com/pinterest/ktlint/releases/tag/1.3.0

**Comment by sanyarnd** [comment]
@freemanjp ? see also #629

**Comment by sanyarnd** [comment]
@freemanjp ping again

**Comment by freemanjp** [comment]
Hi @sanyarnd, sorry for the delay, this is resolved in version [3.3.0](https://github.com/gantsign/ktlint-maven-plugin/releases/tag/3.3.0) of this plugin (allow a couple of hours for it to show up in Maven central).
